const GET_BREED = "GET_BREED";
const SEARCH_DOG = 'SEARCH_DOG';
const DOG_DETAIL = 'DOG_DETAIL';
const CREATE_DOG = 'CREATE_DOG';
const SORT_BY_NAME= 'SORT_BY_NAME';
const SORT_BY_WEIGHT = 'SORT_BY_WEIGHT';
export {
    GET_BREED,
    SEARCH_DOG,
    DOG_DETAIL,
    CREATE_DOG,
    SORT_BY_NAME,
    SORT_BY_WEIGHT
}